GET http://localhost/subscriber/

###

POST  http://localhost/subscriber
Content-Type: application/json

{
    "name" : "moin Uddin Samad",
    "subscribedtochannel":"HelloWorld"
}


###

DELETE http://localhost/subscriber/61d8c6fd640ae6850ed0b171

###

PATCH http://localhost/subscriber/61d8c78d640ae6850ed0b180
Content-Type: application/json

{
    "name":"shayaan mohammed"
}

###

PUT http://localhost/subscriber/61d8c78d640ae6850ed0b180
Content-Type: application/json

{
    "name":"wadood abdul",
    
   
}